{
  imports = [
    ./nec-apc-3
    ./geist-mono
    ./iosevka
    ./zed-mono
    ./victor-mono
    ./cascadia-code
    ./jetbrains-mono
    ./consolas
    ./terminus
    ./sf-mono
    ./cozette
    ./terminess
    ./aporetic-sans-mono
    ./aporetic-serif-mono
    ./monocraft
  ];
}
