#!/usr/bin/env bash
# sets wallpaper temporarily

main () {
  case "$1" in
    "-h" | "--help") help;;
    *) set_wallpaper "$1";;
  esac
}

get_full_path () {
  path="$1"
  if [[ "$path" != "/"* ]]; then
    if [[ "$path" == "~/"* ]]; then
      path="$HOME/${path:2}"
    else
      path="$(pwd)/$path"
    fi
  fi
  echo "$path"
}

help () {
  echo "wptest -- set a wallpaper temporarily"
  echo "usage: wptest <path/to/wallpaper>"
}

set_wallpaper () {
  wallpaper="$(get_full_path "$1")"
  if [ -f "$wallpaper" ]; then
    pkill swaybg
    swaybg -i "$wallpaper" -m fill &
    disown
    notify-send "Wallpaper" "Set temporary wallpaper $wallpaper" -i "$wallpaper"
  else
    echo "Error: file \"$wallpaper\" not found!"
    exit 1
  fi
}

main "$@"
