{
  imports = [
    ./carob
    ./caroline
    ./manuscript
    ./rose-pine-moon
    ./rose-pine
    ./tarot
    ./wizard
    ./embers
    ./twilight
    ./swamp
    ./mountain
    ./terracotta
    ./atelier-savanna
    ./blood-rust
    ./spirit
    ./darkmoss
    ./gruvbox-dark-hard
    ./gruvbox-material-dark-hard
    ./biscuit
    ./everblush
    ./levuaska
    ./mountain-peek
    ./black-metal-khold
    ./oxocarbon
    ./henna
    ./peachy
  ];
}
