{
  imports = [
    ./carob
    ./caroline
    ./manuscript
    ./rose-pine-moon
    ./rose-pine
    ./tarot
    ./wizard
    ./embers
    ./twilight
    ./swamp
    ./mountain
    ./terracotta
    ./atelier-savanna
    ./blood-rust
    ./spirit
    ./darkmoss
    ./gruvbox-dark-hard
    ./gruvbox-material-dark-hard
    ./biscuit-de-sol-dark
    ./biscuit-de-sol-light
    ./biscuit-de-mar-dark
    ./biscuit-de-mar-light
    ./everblush
    ./levuaska
    ./mountain-peek
    ./black-metal-khold
    ./oxocarbon
    ./henna
    ./peachy
    ./mulberry
    ./paradise
    ./jellybeans
    ./far
    ./decay
    ./haze
    ./fyry
    ./terracotta-light
    ./rose-pine-dawn
    ./vase
    ./vesper
    ./petrichor-dew
    ./crayon
    ./substrata
    ./unnamed-1
    ./blue-velvet
    ./moonfly
    ./da-one-black
    ./jardo-brighter
    ./catppuccin-mocha
    ./i-cant-believe-its-not-butter
    ./i-forgor
  ];
}
