{
  windowrulev2 = [
    "suppressevent maximize, class:.*"
    "nomaxsize, title:^(Wine configuration)$"
    "float, class:^(org.kde.kruler)$"
    "float, title:^(HyprViewBinds)$"
    "float, title:^(galculator)$"
    "float, title:^(Open File)(.*)$"
    "float, title:^(Select a File)(.*)$"
    "float, title:^(Open Folder)(.*)$"
    "float, title:^(Save As)(.*)$"
    "fullscreen, title:^((E|e)tterna)(.*)$"
    # "size 640 360, title:(Picture-in-Picture)"
    "pin, title:^(Picture-in-Picture)$"
    "float, title:^(Picture-in-Picture)$"
    "float, title:^(Authentication Required)$"
    "float, title:^(Soundboard)$"
    "plugin:hyprbars:nobar, class:^(org.kde.kruler)"
    "plugin:hyprbars:nobar, title:^(vesktop)$"
    "plugin:hyprbars:nobar, title:^(File Upload)$"
    "plugin:hyprbars:nobar, title:^(Empty Trash)$"
    "plugin:hyprbars:nobar, title:^(File Manager Preferences)$"
    "plugin:hyprbars:nobar, title:^(Choose a color)$"
    "plugin:hyprbars:nobar, title:^(Open File)$"
    "plugin:hyprbars:nobar, title:^(Thunar Preferences)$"
  ];
}
