#!/usr/bin/env python3

import sys
import requests
from bs4 import BeautifulSoup

URL = "https://www.google.com/finance/quote/AUD-USD"

def main():
    argc = len(sys.argv)
    if argc > 2 or argc == 1:
        help()
        exit(1)
    input = sys.argv[1]
    if input == "--help" or input == "-h":
        help()
        exit(0)
    if input.isdigit() == False:
        print("Error: \"" + input + "\" is not a numerical value.")
        exit(1)
    input = int(input)
    r = requests.get(URL)
    if r.status_code != 200:
        print("Error: cannot connect to " + URL + ".")
        exit(1)
    soup = BeautifulSoup(r.content, 'html.parser')
    div = soup.find('div', class_='YMlKec fxKbKc')
    val = div.text.strip()
    if val.replace('.', '', 1).isdigit() == False:
        print("Error: the dev needs to fix the scraper.")
        exit(1)
    val = float(val)
    output = input * val
    print("$" + str(input) + " AUD is equal to $" + str(round(output, 2)) + " USD.")

def help():
    print("audtousd -- yazoink 2024")
    print("a simple AUD to USD converter")
    print("Usage:")
    print("    audtousd (numerical value)")

main()
